# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Metropolis sampler using Rcpp
#' @description A Metropolis sampler using Rcpp
#' @param N the number of samples
#' @param x0 the initial value
#' @param sigma the standard deviation of the normal distribution
#' @return a random sample of size \code{N} 
#' @useDynLib StatComp20064
#' @examples
#' \dontrun{
#' cpp.rw1=Metropolis(sigma=0.05,x0=25,N=2000)
#' plot(1:2000,cpp.rw1[,1],type='l',ylab="x",xlab='iteration',main='sd=0.05(Cpp)')
#' }
#' @export
Metropolis <- function(sigma = 0.05, x0 = 25, N = 2000L) {
    .Call('_StatComp20064_Metropolis', PACKAGE = 'StatComp20064', sigma, x0, N)
}

